// 面试/jwt/TOKEN/src/views/login.vue
<template>
    <van-form @submit="onSubmit">
      <van-cell-group inset>
        <van-field
          v-model="username"
          name="username"
          label="用户名"
          placeholder="用户名"
          :rules="[{ required: true, message: '请填写用户名' }]"
        />
        <van-field
          v-model="password"
          type="password"
          name="password"
          label="密码"
          placeholder="密码"
          :rules="[{ required: true, message: '请填写密码' }]"
        />
      </van-cell-group>
      <div style="margin: 16px;">
        <van-button round block type="primary" native-type="submit">
          登录
        </van-button>
      </div>
    </van-form>
  
  </template>
  
  <script setup>
  import { ref } from 'vue';
  import axios from 'axios'
  
  const username = ref('')
  const password = ref('')
  
  const onSubmit = (values) => {
    console.log(values);
    axios.post('http://localhost:3000/login',values).then((res)=>{
        //后端返回的结果
        console.log(res)
    })
  }
  </script>
  
  <style lang="css" scoped>
  
  </style>

// react/react-demo/src/pages/login/index.jsx
import { Button,  Form, Input } from "antd";
import './index.css'
import { useNavigate as  UseNavigate } from "react-router-dom";
export default function index() {
  const navigate = UseNavigate()
  const onFinish = (values) => {
    console.log("Success:", values);
    navigate("/layout")
  };
  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };
  return (
    <div className="login">
     
      <Form
        name="basic"
        labelCol={{//左侧标签名占据的空间
          span: 8,
        }}
        wrapperCol={{//右侧框占据的空间
          span: 16,
        }}
        style={{
          maxWidth: 600,
        }}
        initialValues={{
          remember: true,
        }}
        onFinish={onFinish}
        onFinishFailed={onFinishFailed}
        autoComplete="off"
      >
        <Form.Item
          label="用户名"
          name="username"
          rules={[
            {
              required: true,
              message: "请输入你的用户名!",
            },
          ]}
        >
          <Input />
        </Form.Item>

        <Form.Item
          label="密码"
          name="password"
          rules={[
            {
              required: true,
              message: "请输入你的密码",
            },
          ]}
        >
          <Input.Password />
        </Form.Item>

       

        <Form.Item
          wrapperCol={{
            offset: 8,
            span: 16,
          }}
        >
          <Button type="primary" htmlType="submit">
            提交
          </Button>
        </Form.Item>
      </Form>
    </div>
  );
}
