// 面试/jwt/client/src/views/Login.vue
<template>
  <van-form @submit="onSubmit">
    <van-cell-group inset>
      <van-field
        v-model="username"
        name="username"
        label="用户名"
        placeholder="用户名"
        :rules="[{ required: true, message: '请填写用户名' }]"
      />
      <van-field
        v-model="password"
        type="password"
        name="password"
        label="密码"
        placeholder="密码"
        :rules="[{ required: true, message: '请填写密码' }]"
      />
    </van-cell-group>
    <div style="margin: 16px;">
      <van-button round block type="primary" native-type="submit">
        登录
      </van-button>
    </div>
  </van-form>

</template>

<script setup>
// import axios from "axios"
import { login } from '../api/user.js'
import { ref } from 'vue';
import { useRouter } from 'vue-router'

const router = useRouter()

const username = ref('')
const password = ref('')

const onSubmit = (values) => {
  console.log(values);
  // // 发请求
  // axios.post('http://localhost:3000/login', values).then((res) => {
  //   console.log(res); // 后端返回的结果
  //   localStorage.setItem('token', res.data.token);
  //   router.push('/home')
  // });
  login(values).then((res) => {
    console.log(res);
    localStorage.setItem('token', res.token);
    router.push('/home')
    // window.location.href = '/home';
  });
}
</script>

<style lang="css" scoped>

</style>

// react/b站/基础知识/my-router-app/src/components/Login.js
import React from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { getRoute } from './../store/userinfo';
import { useDispatch } from "react-redux";
export default function Login() {
  let username = "";
  let password = "";
  const dispatch = useDispatch();
  const nav = useNavigate();
  function sendLogin() {
    axios
      .post("http://localhost:8000/loginIn", {
        username,
        password,
      })
      .then((res) => {
        console.log(res);
        if (res.data.mes === "登录成功") {
          localStorage.setItem("id", res.data.id);

          dispatch(getRoute(res.data.id));

          nav("/page2");
        } else {
          alert("登录失败");
        }
      });
  }
  return (
    <div>
      <label>用户名</label>
      <input
        onInput={(e) => {
          username = e.target.value;
        }}
        type="text"
      />
      <label>密码</label>
      <input
        onInput={(e) => {
          password = e.target.value;
        }}
        type="text"
      />
      <button onClick={sendLogin}>登录</button>
    </div>
  );
}
